### PR TITLE
Added support for Android

### PR DESCRIPTION
**Pull request by yymjr**
as the title shows,I have modified Camke to support Android

### CODE REVIEW

**Comment by kobalicek** [comment]
I have fixed the `simdarm_p.h` header (it has been merged to master) and I'm doing an experiment with build support as well. This PR was a good inspiration to see the problems, however, I have decided to do 2 changes instead and some a little differently.

**Comment by yymjr** [comment]
OK,that is good.Your fix is perfect

**Comment by kobalicek** [comment]
BTW thanks for updating the PR.

I have merged today some changes in this area and I'm wondering whether you would be able to check out the current master branch and try whether it has fixed all the problems you were having?

**Comment by yymjr** [comment]
Of course,It is currently working normally, but the rendering time is more than 100 ms.

**Pull request closed without merging**
